/**
 * The domain model for a project's memory.
 *
 * Everything the scanner learns becomes a Node; everything it learns *about how
 * things relate* becomes an Edge. Both are serialised to Markdown notes (human
 * and Obsidian readable) and mirrored into index.json (machine readable).
 */

export type NodeKind =
  | 'project'
  /** A Cargo workspace member. */
  | 'crate'
  /** A Rust type annotated `#[contract]` — a deployable Soroban contract. */
  | 'contract'
  /** A `pub fn` inside a `#[contractimpl]` block: part of the contract's public interface. */
  | 'function'
  /** A `#[contracttype]` struct or enum. */
  | 'type'
  /** A `#[contracterror]` enum. */
  | 'error'
  /** A `#[contractevent]` or a topic published via `env.events().publish(...)`. */
  | 'event'
  /** A distinct key written to instance/persistent/temporary storage. */
  | 'storage'
  /** A source file that is not itself a contract. */
  | 'module'
  /** A test module or integration test file. */
  | 'test'
  /** A live contract instance on a network, identified by contract ID. */
  | 'deployment'
  /** A build/deploy shell or TS script, Makefile target, or CI job. */
  | 'script'
  /** README, docs/, or any Markdown the project already carries. */
  | 'doc'
  /** Human-authored rationale: why something is the way it is. */
  | 'decision'
  /** Something known to be pending. */
  | 'task'
  /** A token or Stellar Asset Contract this project moves value through. */
  | 'asset';

export type EdgeKind =
  /** Structural containment: crate defines contract, contract defines function. */
  | 'defines'
  /** A cross-contract call, evidenced by `contractimport!` or a generated Client. */
  | 'calls'
  /** A Cargo dependency between crates. */
  | 'depends_on'
  /** A test exercises a contract or function. */
  | 'tests'
  /** A script builds or deploys a contract. */
  | 'deploys'
  /** A contract in source corresponds to a live instance on a network. */
  | 'deployed_as'
  /** A function reads a storage key. */
  | 'reads'
  /** A function writes a storage key. */
  | 'writes'
  /** A function publishes an event. */
  | 'emits'
  /** A function returns or panics with an error variant. */
  | 'raises'
  /** A doc or decision note refers to a node. */
  | 'documents'
  /** A weaker association, e.g. a task mentions a contract. */
  | 'mentions';

/** Where a fact came from. Lets `explain` cite evidence instead of asserting. */
export type Provenance =
  /** Parsed out of source code. */
  | { source: 'source'; file: string; line?: number }
  /** Read from Cargo.toml / a config file. */
  | { source: 'config'; file: string }
  /** Returned by the Stellar CLI, i.e. ground truth from a compiled Wasm or the network. */
  | { source: 'stellar-cli'; command: string; network?: string }
  /** Derived from git history. */
  | { source: 'git'; ref: string }
  /** Written by a human in a note. */
  | { source: 'human'; file: string }
  /** Generated by the optional AI layer — always marked, never confused with fact. */
  | { source: 'ai'; model: string };

export interface MemoryNode {
  /** Stable identity, e.g. `contract:payroll`. Used as the wikilink target. */
  id: string;
  kind: NodeKind;
  /** Display name, e.g. `Payroll`. */
  title: string;
  /** Repo-relative path this node lives at, when it has one. */
  path?: string;
  line?: number;
  /** One-line description. Deterministic when possible, AI-enriched when available. */
  summary?: string;
  /** Kind-specific structured detail. See the payload interfaces below. */
  data?: Record<string, unknown>;
  provenance: Provenance[];
  /** ISO date this node was first observed. */
  firstSeen: string;
  /** ISO date this node last changed. */
  lastChanged: string;
}

export interface MemoryEdge {
  from: string;
  to: string;
  kind: EdgeKind;
  /** Short human-readable reason, e.g. "via contractimport! in lib.rs:12". */
  note?: string;
  provenance: Provenance[];
}

/* ------------------------------------------------------------------ *
 * Kind-specific payloads (stored in MemoryNode.data)
 * ------------------------------------------------------------------ */

export interface ContractData {
  crate: string;
  /** Path to the built .wasm, if one was found. */
  wasmPath?: string;
  /** SHA-256 of the bytes of the local .wasm. Needs no CLI and no network. */
  localWasmHash?: string;
  functions: string[];
  /** Traits implemented via `impl <Trait> for <Type>`, e.g. `token::TokenInterface`. */
  implementsTraits?: string[];
  /** True when the contract can replace its own code in place. */
  upgradeable?: boolean;
  upgradeFn?: string;
}

/**
 * Where the address passed to `require_auth` came from. `guard-macro` covers
 * library attributes such as OpenZeppelin's `#[only_owner]`, which gate a
 * function without any call in its body.
 */
export type AuthOrigin = 'param' | 'storage' | 'current_contract' | 'guard-macro' | 'unknown';

export interface AuthSubjectData {
  expr: string;
  origin: AuthOrigin;
  /** For `storage` origin, the key the address was loaded from. */
  key?: string;
  forArgs: boolean;
}

export interface ErrorData {
  /**
   * Variants and their discriminants. These are published ABI — a client
   * matches on the integer, so renumbering one silently breaks integrations.
   */
  variants: { name: string; code: number }[];
  /** Set when the deployed contract's spec disagrees with this source. */
  deployedMismatch?: string;
  /**
   * Whether the discriminants were compared against the deployed contract at
   * all. An absent field read as "checked and fine" to some consumers and
   * "never checked" to others — opposite answers to a go/no-go question.
   */
  deployedCheck?: 'matches' | 'differs' | 'not-checked';
}

export interface AssetData {
  /** How the client was obtained: an SDK token client, a SAC client, or generated. */
  kind: 'token' | 'stellar-asset' | 'generated';
  /** Where the contract address comes from: caller-supplied or configured. */
  addressOrigin: AuthOrigin;
  addressKey?: string;
  /** Methods this project invokes on it. */
  methods: string[];
}

export interface TestData {
  /** True when the test module calls `env.mock_all_auths()`. */
  mocksAllAuths: boolean;
  /** Number of `#[test]` functions found. */
  testCount: number;
}

export type StorageDurability = 'instance' | 'persistent' | 'temporary';

export interface StorageData {
  durability: StorageDurability;
  /** The DataKey variant or symbol used as the key, when statically resolvable. */
  key: string;
  /** True when a `extend_ttl` call was seen for this key — its absence is a real Soroban footgun. */
  hasTtlExtension: boolean;
}

export interface FunctionData {
  /** Parameter names and Rust types as written. */
  params: { name: string; type: string }[];
  returns?: string;
  /**
   * True when the body calls `require_auth`. On its own this says only that
   * auth happened — see `authSubjects` for whether it gates anything.
   */
  requiresAuth: boolean;
  /** Whose authority is demanded, and where that address came from. */
  authSubjects?: AuthSubjectData[];
  visibility: 'public' | 'internal';
}

export interface DeploymentData {
  network: string;
  contractId: string;
  /** SHA-256 of the Wasm actually installed on the network. */
  onChainWasmHash?: string;
  /** Alias registered with `stellar contract alias add`, if any. */
  alias?: string;
  /** Set when the on-chain hash and the local build disagree. */
  drift?: 'in-sync' | 'stale' | 'unknown';
  /** Soroban SDK / rustc versions reported by `stellar contract info meta`. */
  meta?: Record<string, string>;
}

/* ------------------------------------------------------------------ *
 * The assembled memory
 * ------------------------------------------------------------------ */

export interface ProjectMemory {
  /** Schema version, so a future stellar-memory can migrate an old vault. */
  version: 1;
  project: {
    name: string;
    root: string;
    /** Free-text purpose. Seeded from README, refined by AI or by hand. */
    purpose?: string;
    networks: string[];
  };
  nodes: MemoryNode[];
  edges: MemoryEdge[];
  scans: ScanRecord[];
}

export interface ScanRecord {
  at: string;
  /** Git HEAD at scan time, when the project is a git repo. */
  commit?: string;
  nodeCount: number;
  edgeCount: number;
  /** Node ids added or changed since the previous scan — this is what `resume` reports. */
  changed: string[];
}

export const NODE_KINDS: NodeKind[] = [
  'project', 'crate', 'contract', 'function', 'type', 'error', 'event',
  'storage', 'module', 'test', 'deployment', 'script', 'doc', 'decision', 'task',
];
