[workspace]
resolver = "2"
members = [
    "contracts/payroll",
    "contracts/treasury",
    "contracts/employee-registry",
]

[workspace.package]
version = "0.3.0"
edition = "2021"

[workspace.dependencies]
soroban-sdk = "22.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
codegen-units = 1
lto = true
panic = "abort"
